import { useMemo, useState } from "react"
import slugify from "slugify"
import { useSiteContext } from "../../context/SiteContext"
import axios from "axios"

type SiteFormData = {
    name: string;
    slug: string;
    niche: string;
    domain: string;
}

type Props = {
    initialData: Partial<SiteFormData>;
    onSubmit: (data: SiteFormData) => void;
    loading: boolean;
}

function SiteForm({ initialData, onSubmit, loading = false }: Props) {

    const [formData, setFormData] = useState<SiteFormData>({ name: initialData?.name || "", slug: initialData?.slug || "", niche: initialData?.niche || "", domain: initialData?.domain || "" })


    useMemo(() => {

        if (!formData.name) return;

        const autoGeneratedSlug = slugify(formData.name, {
            lower: true,
            strict: true,
            trim: true
        })

        setFormData((prev) => ({
            ...prev,
            slug: autoGeneratedSlug
        }))

    }, [formData.name])

    return (
        <div>SiteForm</div>
    )
}

export default SiteForm