import { useMemo, useState } from "react";
import slugify from "slugify";
import { useSiteContext } from "../../context/SiteContext";
import axios from "axios"
import Tiptap from "../tiptap/Tiptap";

type PostFormData = {
    title: string;
    slug: string;
    exerpt: string;
    content: string;
    featuredImage: string;
    category: string;
    tags: string[];
    published: boolean;
    seo: {
        metaTitle: string;
        metaDescription: string;
        keywords: string[]
    },
}

type Props = {
    initialData: Partial<PostFormData>;
    onSubmit: (data: PostFormData) => void;
    loading: boolean;
}

const BASE_URL = import.meta.env.VITE_BASE_URL || "http://localhost:3000"

function PostForm({ initialData, onSubmit, loading = false }: Props) {
    const { site } = useSiteContext();

    const [tagInput, setTagInput] = useState("");
    const [keywordInput, setKeywordInput] = useState("");

    const [formData, setFormData] = useState<PostFormData>({
        title: initialData?.title || "",
        slug: initialData?.slug || "",
        exerpt: initialData?.exerpt || "",
        content: initialData?.content || "",
        featuredImage: initialData?.featuredImage || "",
        category: initialData?.category || "",
        tags: initialData?.tags || [""],
        published: initialData?.published || false,
        seo: {
            metaTitle: initialData?.seo?.metaTitle || "",
            metaDescription: initialData?.seo?.metaDescription || "",
            keywords: initialData?.seo?.keywords || [""]
        },
    })

    useMemo(() => {

        if (!formData.title) return

        const autoGeneratedSlug = slugify(formData.title, {
            lower: true,
            strict: true,
            trim: true
        })

        setFormData((prev) => ({
            ...prev,
            slug: autoGeneratedSlug
        }))

    }, [formData.title])

    const handleChange = (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement> | React.ChangeEvent<HTMLSelectElement>) => {

        const { name, value, type } = e.target;

        setFormData((prev) => (
            {
                ...prev,
                [name]: type === "checkbox" ? (e.target as HTMLInputElement).checked : value
            }
        ))
    }

    const handleSeoChange = (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>) => {
        const { name, value } = e.target;

        setFormData((prev) => (
            {
                ...prev,
                seo: {
                    ...prev.seo,
                    [name]: value
                }
            }
        ))
    }

    const handleFeaturedImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {

        const file = e.target.files?.[0];

        if (!file) return;

        try {
            const formData = new FormData();

            formData.append("image", file);

            const response = await axios.post(`${BASE_URL}`, formData);

            const imageUrl = response.data.url;

            setFormData(prev => ({
                ...prev,
                featuredImage: imageUrl
            }))

        } catch (error) {
            console.error("Failed to upload featured image", error)
        }
    }

    return (
        <div>PostForm</div>
    )
}

export default PostForm