import { useMemo, useState } from "react";
import slugify from "slugify";
import { useSiteContext } from "../../context/SiteContext";
import axios from "axios"
import Tiptap from "../tiptap/Tiptap";

type PostFormData = {
    title: string;
    slug: string;
    excerpt: string;
    content: string;
    featuredImage: string;
    category: string;
    tags: string[];
    published: boolean;
    seo: {
        metaTitle: string;
        metaDescription: string;
        keywords: string[]
    },
}

type Props = {
    initialData?: Partial<PostFormData>;
    onSubmit: (data: PostFormData) => void;
    loading: boolean;
}

const BASE_URL = import.meta.env.VITE_BASE_URL || "http://localhost:3000"

function PostForm({ initialData, onSubmit, loading = false }: Props) {
    const { site } = useSiteContext();

    const [tagInput, setTagInput] = useState("");
    const [keywordInput, setKeywordInput] = useState("");

    const [formData, setFormData] = useState<PostFormData>({
        title: initialData?.title || "",
        slug: initialData?.slug || "",
        excerpt: initialData?.excerpt || "",
        content: initialData?.content || "",
        featuredImage: initialData?.featuredImage || "",
        category: initialData?.category || "",
        tags: initialData?.tags || [""],
        published: initialData?.published || false,
        seo: {
            metaTitle: initialData?.seo?.metaTitle || "",
            metaDescription: initialData?.seo?.metaDescription || "",
            keywords: initialData?.seo?.keywords || [""]
        },
    })

    useMemo(() => {

        if (!formData.title) return

        const autoGeneratedSlug = slugify(formData.title, {
            lower: true,
            strict: true,
            trim: true
        })

        setFormData((prev) => ({
            ...prev,
            slug: autoGeneratedSlug
        }))

    }, [formData.title])

    const handleChange = (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement> | React.ChangeEvent<HTMLSelectElement>) => {

        const { name, value, type } = e.target;

        setFormData((prev) => (
            {
                ...prev,
                [name]: type === "checkbox" ? (e.target as HTMLInputElement).checked : value
            }
        ))
    }

    const handleSeoChange = (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>) => {
        const { name, value } = e.target;

        setFormData((prev) => (
            {
                ...prev,
                seo: {
                    ...prev.seo,
                    [name]: value
                }
            }
        ))
    }

    const handleFeaturedImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {

        const file = e.target.files?.[0];

        if (!file) return;

        try {
            const formData = new FormData();

            formData.append("image", file);

            const response = await axios.post(`${BASE_URL}`, formData);

            const imageUrl = response.data.url;

            setFormData(prev => ({
                ...prev,
                featuredImage: imageUrl
            }))

        } catch (error) {
            console.error("Failed to upload featured image", error)
        }
    }

    const addTag = () => {

        if (!tagInput.trim()) return;

        setFormData(prev => ({
            ...prev,
            tags: [...prev.tags, tagInput.trim()]
        }))
    }

    const addKeyword = () => {

        if (!keywordInput.trim()) return;

        setFormData(prev => ({
            ...prev,
            seo: {
                ...prev.seo,
                keywords: [...prev.seo.keywords, keywordInput.toLowerCase().trim()]
            }
        }))

        setKeywordInput("");
    }

    const handleSubmit = (e: React.SubmitEvent<HTMLFormElement>) => {
        e.preventDefault();

        onSubmit(formData);
    }

    return (
        <form onSubmit={handleSubmit} className="space-y-6">

            <div className="bg-white border rounded-xl p-6 space-y-5">
                <div>
                    <h2 className="text-xl font-semibold">Blog Post</h2>
                    <p className="text-sm text-gray-500">Publishing for {" "} <span className="font-medium">{site}</span></p>
                </div>

                <div>
                    <label className="block text-left text-sm font-medium mb-2">Title</label>
                    <input type="text" name="title" value={formData.title} onChange={handleChange} placeholder="Enter title..." className="w-full border rounded-lg px-4 py-3" required />
                </div>

                <div>
                    <label className="block text-left text-sm font-medium mb-2">Slug</label>
                    <input type="text" name="slug" value={formData.slug} onChange={handleChange} className="w-full border rounded-lg px-4 py-3 bg-gray-50" />
                </div>

                <div>
                    <label className="block text-left text-sm font-medium mb-2">Excerpt</label>
                    <textarea name="exerpt" value={formData.excerpt} onChange={handleChange} placeholder="Short blog summary..." className="w-full border rounded-lg px-4 py-3" rows={4} maxLength={300} required/>
                </div>

                <div>
                    <label className="block text-left text-sm font-medium mb-2">Category</label>
                    <input type="text" name="category" value={formData.category} onChange={handleChange} placeholder="e.g., Technology" className="w-full border rounded-lg px-4 py-3" />
                </div>
            </div>
        </form>
    )
}

export default PostForm